### ISSUE TITLE
access to AWS

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/storage-benchmarks#11]
@kaipak will eventually need access to AWS as part of the development of this benchmark suite. Pangeo only has Google Cloud resources.

@rsignell-usgs--I remember that you applied for some AWS credits recently in the context of something Pangeo-related. Any chance you can grant some access to Kai so he can start spinning up on AWS.

In the meantime, Kai can use the $300 automatic free credit granted to all new AWS users (until it runs out). These amount can go surprisingly far if you are only launching VMs.

**Comment by kaipak** [comment]
@jreadey has recently provided me access to https://pangeo.esipfed.org which we'll deploy tests on.
